# Define the system of units to use internally.
InternalUnitSystem:
  UnitMass_in_cgs:     1.9891E43   # 10^10 solar masses 
  UnitLength_in_cgs:   3.08567758E21   # 1 kpc 
  UnitVelocity_in_cgs: 1E5   # km/s
  UnitCurrent_in_cgs:  1   # Amperes
  UnitTemp_in_cgs:     1   # Kelvin


# Parameters governing the time integration
TimeIntegration:
  time_begin: 0.    
  time_end:   4.
  dt_min:     1e-16
  dt_max:     1e-1
  
# Parameters governing the snapshots
Snapshots:
  basename:            box
  time_first:          0. 
  delta_time:          .1
  compression:         1
  
Restarts:
  delta_hours: 0.1      

# Parameters for the self-gravity scheme
Gravity:
  eta:                           0.025  
  MAC:                           geometric 
  theta_cr:                      0.7       # Opening angle (Multipole acceptance criterion)
  mesh_side_length:              1024
  comoving_DM_softening:         0.002807572109935156    # Comoving softening for DM (3.32 ckpc)
  max_physical_DM_softening:     0.002807572109935156   # Physical softening for DM (1.30 pkpc)
  comoving_baryon_softening:     0.002807572109935156     # Comoving softening for baryons (1.79 ckpc)
  max_physical_baryon_softening: 0.002807572109935156     # Physical softening for baryons (0.70 pkpc)
 
# Parameters governing the conserved quantities statistics
Statistics:
  delta_time:          0.1

# Parameters related to the initial conditions
InitialConditions:
  file_name:  ./test.hdf5
  periodic:   0


# Parameters for the hydrodynamics scheme
SPH:
  resolution_eta:                    1.2348   # Target smoothing length in units of the mean inter-particle separation (1.2348 == 48Ngbs with the cubic spline kernel).
  h_min_ratio:                       0.01     # Minimal smoothing length in units of softening.
  h_max:                             1.       # Maximal smoothing length in co-moving internal units.
  CFL_condition:                     0.2      # Courant-Friedrich-Levy condition for time integration.
  minimal_temperature:               100.0    # (internal units)
  initial_temperature:               268.7    # (internal units)
  particle_splitting:                0        # Particle splitting is ON
  particle_splitting_mass_threshold: 7e-4     # (internal units, i.e. 7e6 Msun ~ 4x initial gas particle mass)

# Parameters of the stars neighbour search
Stars:
  resolution_eta:        1.1642   # Target smoothing length in units of the mean inter-particle separation
  h_tolerance:           7e-3
  luminosity_filename:   ./photometry

# Parameters for the Friends-Of-Friends algorithm
FOF:
  basename:                        fof_output  # Filename for the FOF outputs.
  min_group_size:                  256         # The minimum no. of particles required for a group.
  linking_length_ratio:            0.2         # Linking length in units of the main inter-particle separation.
  seed_black_holes_enabled:        1           # Enable seeding of black holes in FoF groups
  black_hole_seed_halo_mass_Msun:  1.0e10      # Minimal halo mass in which to seed a black hole (in solar masses).
  scale_factor_first:              0.05        # Scale-factor of first FoF black hole seeding calls.
  delta_time:                      1.00751     # Scale-factor ratio b   etween consecutive FoF black hole seeding calls.
  
  

# Parameters of the line-of-sight outputs
LineOfSight:
  basename:            eagle_los
  num_along_x:         0
  num_along_y:         0
  num_along_z:         100
  scale_factor_first:  0.1
  delta_time:          1.1

PointMassPotential:
  mass:					1e-10
  timestep_mult:			1000
  growth_per_gyr:			1e-7
  position:				[0,0,0]
  useabspos:				0
# DAB model, there are lots of numbers down here that are no longer used by DAB, but I'm frankly afraid to remove them...
DAB:
  use_subgrid_mass_from_ics:          0
  subgrid_seed_mass_Msun:             1e4             # Black hole subgrid mass at creation time in solar masses.
  use_multi_phase_bondi:              0               # Compute Bondi rates per neighbour particle?
  use_subgrid_bondi:                  0               # Compute Bondi rates using the subgrid extrapolation of the gas properties around the BH?
  with_angmom_limiter:                0               # Are we applying the Rosas-Guevara et al. (2015) viscous time-scale reduction term?
  viscous_alpha:                      1e6             # Normalisation constant of the viscous time-scale in the accretion reduction term
  with_boost_factor:                  0               # Are we using the model from Booth & Schaye (2009)?
  boost_alpha_only:                   0               # If using the boost factor, are we using a constant boost only?
  boost_alpha:                        1.              # Lowest value for the accretion effeciency for the Booth & Schaye 2009 accretion model.
  boost_beta:                         2.              # Slope of the power law for the Booth & Schaye 2009 model, set beta to zero for constant alpha models.
  boost_n_h_star_H_p_cm3:             0.1             # Normalization of the power law for the Booth & Schaye 2009 model in cgs (cm^-3).
  with_fixed_T_near_EoS:              0               # Are we using a fixed temperature to compute the sound-speed of gas on the entropy floor in the Bondy-Hoyle accretion term?
  fixed_T_above_EoS_dex:              0.3             # Distance above the entropy floor for which we use a fixed sound-speed
  fixed_T_near_EoS_K:                 8000            # Fixed temperature assumed to compute the sound-speed of gas on the entropy floor in the Bondy-Hoyle accretion term
  radiative_efficiency:               0.1             # Fraction of the accreted mass that gets radiated.
  use_nibbling:                       0               # Continuously transfer small amounts of mass from all gas neighbours to a black hole [1] or stochastically swallow whole gas particles [0]?
  min_gas_mass_for_nibbling:          9e5             # Minimum mass for a gas particle to be nibbled from [M_Sun]. Only used if use_nibbling is 1.
  max_eddington_fraction:             1.              # Maximal allowed accretion rate in units of the Eddington rate.
  eddington_fraction_for_recording:   0.1             # Record the last time BHs reached an Eddington ratio above this threshold.
  coupling_efficiency:                0.1             # Fraction of the radiated energy that couples to the gas in feedback events.
  AGN_feedback_model:                 MinimumDistance # Feedback modes: Random, Isotropic, MinimumDistance, MinimumDensity
  AGN_use_deterministic_feedback:     1               # Deterministic (reservoir) [1] or stochastic [0] AGN feedback?
  use_variable_delta_T:               1               # Switch to enable adaptive calculation of AGN dT [1], rather than using a constant value [0].
  AGN_with_locally_adaptive_delta_T:  1               # Switch to enable additional dependence of AGN dT on local gas density and temperature (only used if use_variable_delta_T is 1).
  AGN_delta_T_mass_norm:              3e8             # Normalisation temperature of AGN dT scaling with BH subgrid mass [K] (only used if use_variable_delta_T is 1).
  AGN_delta_T_mass_reference:         1e8             # BH subgrid mass at which the normalisation temperature set above applies [M_Sun] (only used if use_variable_delta_T is 1).
  AGN_delta_T_mass_exponent:          0.666667        # Power-law index of AGN dT scaling with BH subgrid mass (only used if use_variable_delta_T is 1).
  AGN_delta_T_crit_factor:            1.0             # Multiple of critical dT for numerical efficiency (Dalla Vecchia & Schaye 2012) to use as dT floor (only used if use_variable_delta_T and AGN_with_locally_adaptive_delta_T are both 1).
  AGN_delta_T_background_factor:      0.0             # Multiple of local gas temperature to use as dT floor (only used if use_variable_delta_T and AGN_with_locally_adaptive_delta_T are both 1).
  AGN_delta_T_min:                    1e7             # Minimum allowed value of AGN dT [K] (only used if use_variable_delta_T is 1).
  AGN_delta_T_max:                    3e9             # Maximum allowed value of AGN dT [K] (only used if use_variable_delta_T is 1).
  AGN_delta_T_K:                      3.16228e8       # Change in temperature to apply to the gas particle in an AGN feedback event [K] (used if use_variable_delta_T is 0 or AGN_use_nheat_with_fixed_dT is 1 AND to initialise the BHs).
  AGN_use_nheat_with_fixed_dT:        0               # Switch to use the constant AGN dT, rather than the adaptive one, for calculating the energy reservoir threshold.
  AGN_use_adaptive_energy_reservoir_threshold: 0      # Switch to calculate an adaptive AGN energy reservoir threshold.
  AGN_num_ngb_to_heat:                1.              # Target number of gas neighbours to heat in an AGN feedback event (only used if AGN_use_adaptive_energy_reservoir_threshold is 0).
  max_reposition_mass:                1e20            # Maximal BH mass considered for BH repositioning in solar masses (large number implies we always reposition).
  max_reposition_distance_ratio:      3.0             # Maximal distance a BH can be repositioned, in units of the softening length.
  with_reposition_velocity_threshold: 0               # Should we only reposition to particles that move slowly w.r.t. the black hole?
  max_reposition_velocity_ratio:      0.5             # Maximal velocity offset of a particle to reposition a BH to, in units of the ambient sound speed of the BH. Only meaningful if with_reposition_velocity_threshold is 1.
  min_reposition_velocity_threshold: -1.0             # Minimal value of the velocity threshold for repositioning [km/s], set to < 0 for no effect. Only meaningful if with_reposition_velocity_threshold is 1.
  set_reposition_speed:               0               # Should we reposition black holes with (at most) a prescribed speed towards the potential minimum?
  threshold_major_merger:             0.333           # Mass ratio threshold to consider a BH merger as 'major'
  threshold_minor_merger:             0.1             # Mass ratio threshold to consider a BH merger as 'minor'
  merger_threshold_type:              2               # Type of velocity threshold for BH mergers (0: v_circ at kernel edge, 1: v_esc at actual distance, with softening, 2: v_esc at actual distance, no softening).
  merger_max_distance_ratio:          3.0             # Maximal distance over which two BHs can merge, in units of the softening length.
  minimum_timestep_Myr:               0.1             # Minimum of the accretion-limited time-step length.
  allow_movement_black_hole:	      1		      # Does not do anything, whoops

 	

